backend:
  name: git-gateway
  branch: main
collections:
  - name: routes
    label: routes
    folder: src/routes
    create: true
    fields:
      - name: title
      - name: nav_label
      - name: body
        widget: markdown
  - name: pages
    label: pages
    folder: src/routes/pages
    create: true
    fields:
      - name: title
      - name: nav_label
      - name: body
        widget: markdown
  - name: nest
    label: nest
    folder: src/nest
    create: true
    nested:
      depth: 100 # max depth to show in the collection tree
      summary: '{{title}}' # optional summary for a tree node, defaults to the inferred title field
    fields:
      - name: title
      - name: nav_label
      - name: body
        widget: markdown
media_folder: "static/uploads"
public_folder: "/uploads"

# site_url: https://your-site.com
# display_url: https://your-site.com
# logo_url: https://your-site.com/images/logo.svg
